# https://pre-commit.com/
# Установка:
#   заходим в каталог с проектом и выполняем `pip install pre-commit`
#   рядом с setup.cfg создаем файл `.pre-commit-config.yaml` с содержимым этого файла
# Запуск полного сканирования:
#   из корня проекта запускаем команду `pre-commit run --all-files`

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    # Хуки pre-commit для валидации-исправления базовых ошибок.
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: requirements.txt
      - id: trailing-whitespace

  - repo: https://github.com/myint/autoflake
    # Проверка неиспользуемых импортов и переменных.
    rev: v2.2.0
    hooks:
      - id: autoflake
        args: [ --remove-all-unused-imports, --remove-unused-variables ]

  - repo: https://github.com/pycqa/isort
    # Сортировка импортов
    rev: '5.12.0'
    hooks:
      - id: isort
        args:
          - "--line-length=79"
          - "--multi-line=3"
          - "--trailing-comma"
          - "--force-grid-wrap=0"
          - "--use-parentheses"

  - repo: https://github.com/psf/black
    # Автоформатирование длинны строки.
    rev: '23.3.0'
    hooks:
      - id: black
        language_version: python3.10
        args:
          - "--line-length=79"
          - "--skip-string-normalization"

  - repo: https://github.com/PyCQA/flake8
    # Проверка кода на соответствие PEP8, включая наличие докстрингов.
    rev: '6.0.0'
    hooks:
        - id: flake8
          exclude: |
            (?x)^(
                tests/.*|
                venv/.*|
                env/.*
            )$
          additional_dependencies:
            - pyproject-flake8
            - flake8-builtins
            - flake8-bugbear
            - flake8-eradicate
            - flake8-printf-formatting
            - flake8-pytest-style
            - flake8-variables-names
            - flake8-isort
            - pep8-naming
            - flake8-broken-line
            - flake8-return
            - flake8-docstrings
          args:
            - "--ignore=D104,W503,R503,R504"
            - "--max-complexity=10"
