repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: requirements.txt
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args:
          - "--line-length=79"
          - "--multi-line=3"
          - "--trailing-comma"
          - "--force-grid-wrap=0"
          - "--use-parentheses"

  - repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
      - id: black
        language_version: python3.10
        args:
          - "--line-length=79"
          - "--skip-string-normalization"

  - repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
        - id: flake8
          exclude: |
            (?x)^(
                tests/.*|
                venv/.*|
                env/.*
            )$
          additional_dependencies:
            - pyproject-flake8
            - flake8-builtins
            - flake8-bugbear
            - flake8-eradicate
            - flake8-printf-formatting
            - flake8-pytest-style
            - flake8-variables-names
            - flake8-isort
            - pep8-naming
            - flake8-broken-line
            - flake8-return
            - flake8-docstrings
          args:
            - "--ignore=D104,W503,R503,R504"
            - "--max-complexity=10"
